export const masterDataConfig: Record<string, {
  tableName: string
  title: string
  addButtonText: string
  dialogTitle: string
  dialogDescription: string
  inputPlaceholder?: string
}> = {
  "gender": {
    tableName: "master_gender",
    title: "Gender",
    addButtonText: "Add Gender",
    dialogTitle: "Add Gender",
    dialogDescription: "Enter a new gender value to add to the list.",
    inputPlaceholder: "e.g., Male, Female, Other",
  },
  "skin-colour": {
    tableName: "master_skin_colour",
    title: "Skin Colour",
    addButtonText: "Add Skin Colour",
    dialogTitle: "Add Skin Colour",
    dialogDescription: "Enter a new skin colour value to add to the list.",
    inputPlaceholder: "e.g., Fair, Medium, Dark",
  },
  "body-type": {
    tableName: "master_body_type",
    title: "Body Type",
    addButtonText: "Add Body Type",
    dialogTitle: "Add Body Type",
    dialogDescription: "Enter a new body type value to add to the list.",
    inputPlaceholder: "e.g., Slim, Average, Athletic",
  },
  "marital-status": {
    tableName: "master_marital_status",
    title: "Marital Status",
    addButtonText: "Add Marital Status",
    dialogTitle: "Add Marital Status",
    dialogDescription: "Enter a new marital status value to add to the list.",
    inputPlaceholder: "e.g., Single, Married, Divorced",
  },
  "food-preferences": {
    tableName: "master_food_preferences",
    title: "Food Preferences",
    addButtonText: "Add Food Preference",
    dialogTitle: "Add Food Preference",
    dialogDescription: "Enter a new food preference value to add to the list.",
    inputPlaceholder: "e.g., Vegetarian, Non-Vegetarian, Vegan",
  },
  "indian-languages": {
    tableName: "master_indian_languages",
    title: "Indian Languages",
    addButtonText: "Add Indian Language",
    dialogTitle: "Add Indian Language",
    dialogDescription: "Enter a new Indian language value to add to the list.",
    inputPlaceholder: "e.g., Hindi, Tamil, Telugu",
  },
  "international-languages": {
    tableName: "master_international_languages",
    title: "International Languages",
    addButtonText: "Add International Language",
    dialogTitle: "Add International Language",
    dialogDescription: "Enter a new international language value to add to the list.",
    inputPlaceholder: "e.g., English, French, Spanish",
  },
  "education-level": {
    tableName: "master_education_level",
    title: "Education Level",
    addButtonText: "Add Education Level",
    dialogTitle: "Add Education Level",
    dialogDescription: "Enter a new education level value to add to the list.",
    inputPlaceholder: "e.g., High School, Bachelor's, Master's",
  },
  "degree-qualification": {
    tableName: "master_degree_qualification",
    title: "Degree/ Qualification",
    addButtonText: "Add Degree/ Qualification",
    dialogTitle: "Add Degree/ Qualification",
    dialogDescription: "Enter a new degree/qualification value to add to the list.",
    inputPlaceholder: "e.g., B.Tech, MBA, M.Sc",
  },
  "status": {
    tableName: "master_status",
    title: "Status",
    addButtonText: "Add Status",
    dialogTitle: "Add Status",
    dialogDescription: "Enter a new status value to add to the list.",
    inputPlaceholder: "e.g., Active, Inactive, Pending",
  },
  "employment-type": {
    tableName: "master_employment_type",
    title: "Employment Type",
    addButtonText: "Add Employment Type",
    dialogTitle: "Add Employment Type",
    dialogDescription: "Enter a new employment type value to add to the list.",
    inputPlaceholder: "e.g., Employee, Business, Student",
  },
  "sector": {
    tableName: "master_sector",
    title: "Sector",
    addButtonText: "Add Sector",
    dialogTitle: "Add Sector",
    dialogDescription: "Enter a new sector value to add to the list.",
    inputPlaceholder: "e.g., IT, Finance, Healthcare",
  },
  "type-of-business": {
    tableName: "master_type_of_business",
    title: "Type of Business",
    addButtonText: "Add Type of Business",
    dialogTitle: "Add Type of Business",
    dialogDescription: "Enter a new type of business value to add to the list.",
    inputPlaceholder: "e.g., Retail, Manufacturing, Services",
  },
  "course-degree": {
    tableName: "master_course_degree",
    title: "Course/ Degree",
    addButtonText: "Add Course/ Degree",
    dialogTitle: "Add Course/ Degree",
    dialogDescription: "Enter a new course/degree value to add to the list.",
    inputPlaceholder: "e.g., Computer Science, Business Administration",
  },
  "year-of-study": {
    tableName: "master_year_of_study",
    title: "Year of Study",
    addButtonText: "Add Year of Study",
    dialogTitle: "Add Year of Study",
    dialogDescription: "Enter a new year of study value to add to the list.",
    inputPlaceholder: "e.g., First Year, Second Year, Final Year",
  },
  "caste": {
    tableName: "master_caste",
    title: "Caste",
    addButtonText: "Add Caste",
    dialogTitle: "Add Caste",
    dialogDescription: "Enter a new caste value to add to the list.",
    inputPlaceholder: "e.g., Brahmin, Kshatriya, Vaishya",
  },
  "subcaste": {
    tableName: "master_subcaste",
    title: "Subcaste",
    addButtonText: "Add Subcaste",
    dialogTitle: "Add Subcaste",
    dialogDescription: "Enter a new subcaste value to add to the list.",
    inputPlaceholder: "Enter subcaste value",
  },
  "kulam": {
    tableName: "master_kulam",
    title: "Kulam",
    addButtonText: "Add Kulam",
    dialogTitle: "Add Kulam",
    dialogDescription: "Enter a new kulam value to add to the list.",
    inputPlaceholder: "Enter kulam value",
  },
  "gotram": {
    tableName: "master_gotram",
    title: "Gotram",
    addButtonText: "Add Gotram",
    dialogTitle: "Add Gotram",
    dialogDescription: "Enter a new gotram value to add to the list.",
    inputPlaceholder: "Enter gotram value",
  },
  "family-type": {
    tableName: "master_family_type",
    title: "Family Type",
    addButtonText: "Add Family Type",
    dialogTitle: "Add Family Type",
    dialogDescription: "Enter a new family type value to add to the list.",
    inputPlaceholder: "e.g., Nuclear, Joint, Extended",
  },
  "family-status": {
    tableName: "master_family_status",
    title: "Family Status",
    addButtonText: "Add Family Status",
    dialogTitle: "Add Family Status",
    dialogDescription: "Enter a new family status value to add to the list.",
    inputPlaceholder: "e.g., Middle Class, Upper Middle Class",
  },
  "zodiac-moon-sign": {
    tableName: "master_zodiac_moon_sign",
    title: "Zodiac or Moon Sign",
    addButtonText: "Add Zodiac or Moon Sign",
    dialogTitle: "Add Zodiac or Moon Sign",
    dialogDescription: "Enter a new zodiac or moon sign value to add to the list.",
    inputPlaceholder: "e.g., Aries, Taurus, Gemini",
  },
  "star": {
    tableName: "master_star",
    title: "Star",
    addButtonText: "Add Star",
    dialogTitle: "Add Star",
    dialogDescription: "Enter a new star value to add to the list.",
    inputPlaceholder: "e.g., Ashwini, Bharani, Krittika",
  },
  "lagnam": {
    tableName: "master_lagnam",
    title: "Lagnam",
    addButtonText: "Add Lagnam",
    dialogTitle: "Add Lagnam",
    dialogDescription: "Enter a new lagnam value to add to the list.",
    inputPlaceholder: "Enter lagnam value",
  },
  "hobbies": {
    tableName: "master_hobbies",
    title: "Hobbies",
    addButtonText: "Add Hobby",
    dialogTitle: "Add Hobby",
    dialogDescription: "Enter a new hobby value to add to the list.",
    inputPlaceholder: "e.g., Reading, Cooking, Traveling",
  },
  "interests": {
    tableName: "master_interests",
    title: "Interests",
    addButtonText: "Add Interest",
    dialogTitle: "Add Interest",
    dialogDescription: "Enter a new interest value to add to the list.",
    inputPlaceholder: "e.g., Music, Sports, Art",
  },
  "smoking": {
    tableName: "master_smoking",
    title: "Smoking",
    addButtonText: "Add Smoking",
    dialogTitle: "Add Smoking",
    dialogDescription: "Enter a new smoking value to add to the list.",
    inputPlaceholder: "e.g., Never, Occasionally, Regularly",
  },
  "drinking": {
    tableName: "master_drinking",
    title: "Drinking",
    addButtonText: "Add Drinking",
    dialogTitle: "Add Drinking",
    dialogDescription: "Enter a new drinking value to add to the list.",
    inputPlaceholder: "e.g., Never, Occasionally, Socially",
  },
  "parties": {
    tableName: "master_parties",
    title: "Parties",
    addButtonText: "Add Parties",
    dialogTitle: "Add Parties",
    dialogDescription: "Enter a new parties value to add to the list.",
    inputPlaceholder: "e.g., Never, Occasionally, Regularly",
  },
  "pubs": {
    tableName: "master_pubs",
    title: "Pubs",
    addButtonText: "Add Pubs",
    dialogTitle: "Add Pubs",
    dialogDescription: "Enter a new pubs value to add to the list.",
    inputPlaceholder: "e.g., Never, Occasionally, Regularly",
  },
}

